include: package:flutter_lints/flutter.yaml

linter:
  rules:
    constant_identifier_names: false
    use_build_context_synchronously: false
    prefer_const_declarations: true
    prefer_const_constructors: true

formatter:
  trailing_commas: preserve