name: sinflix
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Data
  get_it: ^8.0.3
  retrofit: ^4.6.0
  flutter_bloc: ^9.1.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.5.3
  
  # UI
  intl: ^0.20.2
  lottie: ^3.3.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  easy_localization: ^3.0.7+1
  cached_network_image: ^3.4.1

  # Firebase
  firebase_analytics: ^11.5.2
  firebase_crashlytics: ^4.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
  # Code generation
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Euclid Circular A
      fonts:
        - asset: assets/fonts/Euclid-Circular-A-Regular.ttf
        - asset: assets/fonts/Euclid-Circular-A-Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid-Circular-A-Light.ttf
          weight: 300
        - asset: assets/fonts/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-A-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid-Circular-A-Italic.ttf
          style: italic
        - asset: assets/fonts/Euclid-Circular-A-Light-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Euclid-Circular-A-Medium-Italic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Euclid-Circular-A-SemiBold-Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Euclid-Circular-A-Bold-Italic.ttf
          weight: 700
          style: italic 